### ISSUE TITLE
EODataAccessGateway 

### ISSUE THREAD

**Issue by carolinepacheco** [CS-SI/eodag-cube#10]
Hi, 

It is my first time using this library and every time I run:

dag = EODataAccessGateway()

I get the following error:

expected '<document start>', but found '<scalar>'
  in "/opt/anaconda3/lib/python3.8/site-packages/eodag/resources/providers.yml", line 1595, column 1

Can someone please help me solve this problem?

**Comment by sbrunato** [comment]
Hi @carolinepacheco and thank you for reporting this issue. 
I have just tried to install eodag in a clean environment using `conda install -c conda-forge eodag`, but got no error.
Can you please provide some more information:
- your eodag version:
```sh
eodag version
```
- the output of:
```sh
sed -n "1590,1600p" /opt/anaconda3/lib/python3.8/site-packages/eodag/resources/providers.yml
```
Thank you

**Comment by carolinepacheco** [comment]
Hi @sbrunato,

Thanks for your quick reply.
I reinstalled anaconda, then I followed your instructions and It is now working properly.

Thanks a lot!
