### ISSUE TITLE
Wrong DaraArray shape from get_data() method on EOProduct

### ISSUE THREAD

**Issue by ClaudioCiociola** [CS-SI/eodag-cube#11]
**Bug description**
The `.get_data()` method that is usable on the `EOProduct` object is bugged and return a `DataArray` with the inverted shape.
Asking for a rectangular selection, for example an extent with the height of 2 km and the width of 1 km in the `EPSG:32632`, looks like `(926132.1981, 4592486.0233, 926132.1981 + 2000, 4592486.0233 + 1000)` but the output `DataArray` has is shape equals to `(100, 200)` with 10 meter resolution, so the height and the width are flipped.

**Code to reproduce**
This is the basic code used:
```
import rasterio as rs
from eodag.api.core import EODataAccessGateway
from eodag.utils.logging import setup_logging

setup_logging(verbose=3)
dag = EODataAccessGateway()

products, estimated_nbr_of_results = dag.search(
    productType=product_type,
    start='2020-11-01',
    end='2020-11-30',
    geom=extent,
    cloudCover=1
)

product = products[0]
product.download()

crs = 'epsg:32632'
resolution = 10
sub_extent = (926132.1981, 4592486.0233, 926132.1981 + 2000, 4592486.0233 + 1000)

VIR = product.get_data(band='B04', extent=sub_extent, crs=crs, resolution=resolution)  # here the shape is already (100, 200), instead of (200, 100)
NIR = product.get_data(band='B08', extent=sub_extent, crs=crs, resolution=resolution)  # here the shape is already (100, 200), instead of (200, 100)
NDVI = (NIR - VIR * 1.) / (NIR + VIR)  # here the shape is already (100, 200), instead of (200, 100)

with rs.open(f"ndvi_test_20.tif", "w",
             driver='GTiff',
             count=1,
             crs=crs,
             transform=rs.transform.from_origin(sub_extent[0], sub_extent[3], resolution, resolution),
             nodata=-9999.0,
             height=NDVI.shape[0],
             width=NDVI.shape[1],
             dtype=str(NDVI.dtype)) as ndvi_tif:
    ndvi_tif.write(NDVI, 1)  # and here the raster created is the 1st image posted below in the Output section
```

**Output**
As result, you obtain a stretched array and also raster if you try to save it. You can see the result below with the library output and after fixing this issue:

_Ouput from library_
![Immagine 2021-06-17 105702](https://user-images.githubusercontent.com/43550066/122365599-166abe80-cf5b-11eb-914a-15db152b07c7.png)

_Correct output after fix_
![Immagine 2021-06-17 105629](https://user-images.githubusercontent.com/43550066/122365585-12d73780-cf5b-11eb-9903-e4aceb404f1a.png)

**_Fix / Solution_**
I found that the problem is in the `eodag_cube/api/product/_product.py` where the `WarpedVRT` creates the array... all calculation are done correctly but the `out_shape` has its value flipped as you can see here:
https://github.com/CS-SI/eodag-cube/blob/develop/eodag_cube/api/product/_product.py#L108

All libraries, includin numpy, xarray and rasterio (used here to wrap out the array needed) use the shape in the format of tuple (height, width), so the fix it's just to change the order of the param to match what the dependencies library expect.

**Environment:**
 - Python version: 3.7.9 & 3.8.9 (both tested)
 - EODAG version: 2.3.0b1
 - eodag-cube version: 0.1.1

**Comment by sbrunato** [comment]
Hello @ClaudioCiociola , many thanks for submitting this issue and the associated fix!

We'll check and implement it as soon as possible.
