### ISSUE TITLE
Align variable name in generated xarray with xarray default behavior.

### ISSUE THREAD

**Issue by alambare** [CS-SI/eodag-cube#75]
Replace the hardcoded band variable in xarray generated by get_data().

Replicate the behavior of xarray to generate the variable name.

**Comment by amarandon** [comment]
Note that it's not only the name of the dimension but also the values which currently get transformed by eodag-cube. For instance if the data returned by xarray has a `time` dimensions with values such as
```
array(['2021-01-15T00:00:00.000000000', '2021-01-16T00:00:00.000000000',
       '2021-01-17T00:00:00.000000000', '2021-01-18T00:00:00.000000000'],
      dtype='datetime64[ns]')
```
eodag-cubes produces a `DataArray` with with a dimension named `band` which contains the values:
```
array([1, 2, 3, 4])
```

**Comment by amarandon** [comment]
For the record, I noticed that 

- the `time` dimension is renamed to `band` and its values are changed from dates to integers
- the `DataArray` returned by eodag-cube is shifted by 180° along the x axis (longitude):

```py
eodag_da[1, 8].plot()
```
![image](https://github.com/user-attachments/assets/56bff5bd-40c2-49ff-ba38-30ff69b6c101)
```py
xr_da = xr.open_dataarray(path)
xr_da[1, 8].plot()
```
![image](https://github.com/user-attachments/assets/0cf7a879-1e7c-457f-a4a8-ad3c04f355e2)

**Comment by sbrunato** [comment]
Won't implement in favor of https://github.com/CS-SI/eodag-cube/issues/78
